### ISSUE TITLE
Feature request. NBT Data reader.

### ISSUE THREAD

**Issue by MAGGen-hub** [SamsTheNerd/ducky-periphs#11]
In 1.19.2 we have no nbt data accessors for computer craft. So please if it posible - add block that can be used to read nbt data from block it's facing like in Advanced Peripherals. Stuff like this alow to access and control a lot of processes in game, and I realy miss this feature in 1.19.2 fabric...

**Comment by SamsTheNerd** [comment]
i believe srendi has been talking about porting AP to architectury/fabric for a while now. 

I'm guessing they'll get to that before I would get around to adding this.
