### ISSUE TITLE
Focal port recipe in game and wiki dont match up

### ISSUE THREAD

**Issue by walksanatora** [SamsTheNerd/ducky-periphs#15]
in-game:
![image](https://user-images.githubusercontent.com/47339836/233409272-bccfad8e-5c9b-4e5c-b2f6-0e0ae5f5254e.png)
wiki: ![other](https://github.com/SamsTheNerd/ducky-periphs/wiki/images/recipes/focal_port_recipe.png)

**Comment by SamsTheNerd** [comment]
yeahh, i need to update some of the documentation, just haven't gotten around to it

**Comment by SamsTheNerd** [comment]
fixed
