### ISSUE TITLE
Empty focus acts weird in focal port

### ISSUE THREAD

**Issue by maraxin** [SamsTheNerd/ducky-periphs#16]
If you use empty focus in focal port and then try to take it out, it'll still keep this empty focus, so you can use PC in order to edit focus, while its in your inventory. Here is a video showing it (I am on quilt 1.19.2)

https://user-images.githubusercontent.com/53759232/235314942-85c8158d-55a1-4986-9387-81af2edcbc60.mp4

**Comment by maraxin** [comment]
![2023-04-29_20 09 48](https://user-images.githubusercontent.com/53759232/235315061-459d241b-ae8e-47d3-bf04-b9790318597f.png)
By the way, if you try to read empty focus, it will throw java error, instead of CC one

**Comment by SamsTheNerd** [comment]
likely same issue as #13 - will fix after archtectury rewrite

**Comment by SamsTheNerd** [comment]
should be fixed in v1.2.0
