### ISSUE TITLE
NULL iota in list deseralization error

### ISSUE THREAD

**Issue by walksanatora** [SamsTheNerd/ducky-periphs#17]
so if you serialize [1,2,NULL,3] for example lua will read it as {1,2, [4] = 3} (so far fine)
and json serializing it leads to [1,2,null,3] and deseralizing that json leads to {1,2, [4] = 3} (still fine)
but when writing that to the focal port since it expects a "continuous" list (1,2,3,4) not 1,2,4 (skipping 3) it leads to the focal port writing garbage
my 2 cents: have (de)seralize have a .size value also so we can have NULL at the end of list

**Comment by SamsTheNerd** [comment]
fixed in v1.2.0
