### ISSUE TITLE
Issue when writing to a focus via a focal port with MoreIotas installed

### ISSUE THREAD

**Issue by zjdtmkhzt** [SamsTheNerd/ducky-periphs#18]
I seem to be experiencing an issue trying to use a focal port, apologies if this is a known issue or user error!
I was also unsure if this should be reported here or on MoreIota's end, please let me know if the problem is on their end!

1. Place down an advanced computer with a focal port on top.
2. Insert focus into focal port.
3. Try to write something to the focus.
![image](https://github.com/SamsTheNerd/ducky-periphs/assets/35579460/604c3101-8b60-4e5d-bac9-b1d1adf8908c)

![image](https://github.com/SamsTheNerd/ducky-periphs/assets/35579460/eb5f13d9-c634-4463-9177-603ce8652440)

This does not seem to occur without MoreIotas installed.

My used mods in this were:
![image](https://github.com/SamsTheNerd/ducky-periphs/assets/35579460/262dca40-76d9-4e0f-82c2-7a46d5fcef0d)

Forge version was 43.2.0.

**Comment by SamsTheNerd** [comment]
yeep, looks like i just forgot to replace a FabricLoader with Platform when I was doing the architectury rewrite: https://github.com/SamsTheNerd/ducky-periphs/blob/c4764ea412584c0cd6ee91b1b3238dc7e89fbccd/common/src/main/java/com/samsthenerd/duckyperiphs/hexcasting/utils/IotaLuaUtils.java#L146 I'll fix it in the next update.

I think the issue should only happen if you try to write an iota from moreIotas or hexal or if you try to write something that wouldn't get properly translated anyways (so something that would just end up writing Garbage). From some brief testing it seems like everything else should still work fine
