### ISSUE TITLE
Focal port gate writing

### ISSUE THREAD

**Issue by ChloeTax** [SamsTheNerd/ducky-periphs#23]
reading an entity bound gate crashes the computer,
![image](https://github.com/SamsTheNerd/ducky-periphs/assets/119641630/5f42d613-620f-4329-8107-5cba681b5da7)
and writing a location bound gate makes a new drifting gate with the same id, so you could put someone on the location bound gate, close the new drifting one, and teleport them anywhere

**Comment by SamsTheNerd** [comment]
fixed the first bit in v1.2.3. second part is a side effect of hexal's gate numbers resetting. Not much I can do to fix it - open to ideas for ways to work around it though.
