### ISSUE TITLE
Suggestion: Ender modem inspired focal link

### ISSUE THREAD

**Issue by anna-s-h** [SamsTheNerd/ducky-periphs#33]
an upgrade to the focal link with extremely long range, costing ender modem(s) instead of wireless, and probably other expensive mats (perhaps mindflaying?). It also should not draw particles.

**Comment by anna-s-h** [comment]
I have been thinking about it, and a much better alternative to hex-based infinite range player networking would just be to have events for changes to a focus in a focal link.

**Comment by SamsTheNerd** [comment]
yeah, sounds like you can just do that in game. If you wanted to have it link based I think just using a network of hexal relays would fit better than infinite range link.
