### ISSUE TITLE
cardinal components required for sucessful worldgen, but this is not documented anywhere.

### ISSUE THREAD

**Issue by Maxwelldoug** [SamsTheNerd/ducky-periphs#35]
Working on a modpack, and get invalid player data trying to load worlds after adding this mod, and CTD trying to create a new one. one of my testers, after investigating the source code, discovered that installing cardinal components fixes this. not sure if this is intended behaviour, but it should possibly be documented. I can provide more information if necessary,

**Comment by SamsTheNerd** [comment]
Yeah, definitely not intended behavior. There was a bug like this a while ago with [this issue](https://github.com/SamsTheNerd/ducky-periphs/issues/6) but that should be resolved? 

Few questions:
- are you using hexcasting ?
- what version of ducky are you using ?
- can you give a crash/error log?

**Comment by Maxwelldoug** [comment]
No HexCasting, ducky 1.20.1-1.3.1 - I've included the log below, and a link to my server with a copy of a modpack version that works. Upon further investigation, exactly 3 things fix the issue - Weird to find hephaestus being involved, but I'm In over my head trying to figure out how it's related.

> Remove Ducky Periphs
> Add Cardinal Components API
> Remove Hephaestus

https://mmacneill.xyz/assets/duckycausesissues.mrpack
[latest.log](https://github.com/SamsTheNerd/ducky-periphs/files/13171728/latest.log)

**Comment by SamsTheNerd** [comment]
ok so from Pyrofab on the CCA discord:

> alright so what's happening is that the user had some CCA modules installed but not the item module
since you are using the cardinal-components entrypoint, your initializer gets loaded as soon as one module exists

I'll fix the next time I work on the mod, but for now yeah just install CCA
