### ISSUE TITLE
Focal Port cannot produce a List Iota

### ISSUE THREAD

**Issue by jojotastic777** [SamsTheNerd/ducky-periphs#4]
Steps to reproduce:
1. Place a Focal Port on the left side of a computer.
2. Write a List Iota (for example, `[1.00]`) to the Focal Port using the Chronicler's Gambit.
3. Run the following code on that computer:
```lua
local focus = peripheral.wrap("left")
focus.writeIota(focus.readIota())
```
4. Focal Port now contains garbage.

**Comment by SamsTheNerd** [comment]
fixed in v1.1.3
