### ISSUE TITLE
Game crashes while generating a world if Hexcasting is not installed

### ISSUE THREAD

**Issue by kuylar** [SamsTheNerd/ducky-periphs#6]
[Crash log](https://github.com/SamsTheNerd/ducky-periphs/files/10924734/crash-2023-03-08_22.55.31-server.txt)

The modrinth page said that hexcasting was optional, is that not the case?

**Comment by SamsTheNerd** [comment]
oops, yeah hexcasting *should* be optional.

I think it was an issue with cardinal components trying to register hex casting stuff that wasn't there, no idea why it was doing that. I moved all hex casting imports out of the DuckyCastingCC init file and it seemed to fix it for me.

Let me know if [this build](https://github.com/SamsTheNerd/ducky-periphs/blob/main/Releases/ducky-periphs-%5B1.19.2%5D-1.1.4.jar) fixes it for you or not.

**Comment by kuylar** [comment]
Yup, seems to be fixed, thanks!
