### ISSUE TITLE
conflict with Moreiotas

### ISSUE THREAD

**Issue by troyheady2** [SamsTheNerd/ducky-periphs#8]
Looks like an incompatibility with moreiotas

I loaded an [ Mind's Reflection ] from the hex side
on the lua terminal 
ran 
x = peripheral.wrap("right")
x.readIota()

Java Exception Thrown:
java.lang.NoClassDefFoundError:
ram/talia/moreiotas/api/spell/StringIota

was unsure if I should post here or on moreiotas..... starting here

**Comment by SamsTheNerd** [comment]
yep that's my bad, I set up some files weirdly and it's doing that for moreIotas and hexal. It was a quick fix, I'll push it in 1.1.5 along with a few other things in a little bit

**Comment by troyheady2** [comment]
Thank you!  and I love the idea of interacting with computer craft for data / hex stuff

**Comment by SamsTheNerd** [comment]
fixed in v1.1.5. sorry it took a minute, those "other things" took a lot longer than I expected.
